chore: remove useless file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -5,7 +5,8 @@ on:
   pull_request:
     branches: [ main, master ]
 jobs:
-  build-and-start-server:
+  build-and-start-server-and-run-e2e-tests:
+    timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
@@ -16,24 +17,28 @@ jobs:
       run: |
         npm install -g yarn && yarn
         yarn build
-        yarn start
-  test:
-    timeout-minutes: 60
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
-      with:
-        node-version: lts/*
-    # - name: Install dependencies
-    #   run: npm install -g yarn && yarn
+        yarn start &
+      env:
+          CI: true
+          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
+          PERSONAL_GITHUB_ACCESS_TOKEN: ${{secrets.PERSONAL_GITHUB_ACCESS_TOKEN}}
     - name: Install Playwright Browsers
-      run: yarn playwright install --with-deps
+      run: npx playwright install --with-deps
     - name: Run Playwright tests
-      run: yarn playwright test
+      run: npx playwright test
     - uses: actions/upload-artifact@v4
       if: always()
       with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
+  block-push:
+    name: Block Push on Failure
+    runs-on: ubuntu-latest
+    needs: build-and-start-server-and-run-e2e-tests
+    if: ${{ failure() }}
+    steps:
+      - name: Block Push
+        run: |
+          echo "Tests failed. Pushing code is not allowed."
+          exit 1
